apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-php-docker-helloworld
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: example-php-docker-helloworld
  template:
    metadata:
      labels:
        app: example-php-docker-helloworld
    spec:
      containers:
      - image: appuio/example-php-docker-helloworld
        name: example-php-docker-helloworld
        ports:
        - containerPort: 8080